Add database 2
kompasvideo/java-filmorate pull request #8
Opened 2022-06-26 18:13 UTC by kompasvideo

2022-06-26 19:46 UTC, eugene-lenkevich requested changes
Привет, Андрей , спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-26 19:46 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (user.isEmpty()) {
У Optional есть метод orElseThrow, с помощью его можно записать этот код короче :)

2022-06-26 19:46 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public User getUserToId(int userId) {
getUserById  - так назвать лучше :)

2022-06-26 19:46 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmDbStorage.java
> +        return genreList.size() == 0 ? null : genreList;
Лучше все же возвращать пустой список, а не null, так проще, не надо проверять на нулл :)

2022-06-26 19:46 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/InMemoryFilmStorage.java
> +        log.info(String.format("Фильм %s успешно добавлен", film));
log.info("Фильм {} успешно добавлен", film);

Вот так, все нужное уже есть :)

2022-06-26 21:29 UTC, kompasvideo commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public User getUserToId(int userId) {
выполнено

2022-06-26 21:29 UTC, kompasvideo commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/InMemoryFilmStorage.java
> +        log.info(String.format("Фильм %s успешно добавлен", film));
выполнено

2022-06-26 21:29 UTC, kompasvideo commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (user.isEmpty()) {
выполнено

2022-06-26 21:31 UTC, kompasvideo commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmDbStorage.java
> +        return genreList.size() == 0 ? null : genreList;
Тесты на Postman требуют  null или список, при пустом списке []  возникает ошибка

2022-06-27 04:35 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmDbStorage.java
> +        return genreList.size() == 0 ? null : genreList;
А ну ок

2022-06-27 04:36 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-27 15:30 UTC, merged